# Generated by Django 4.2.1 on 2023-05-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murimi', '0002_disease_cropdisease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='image',
        ),
        migrations.AddField(
            model_name='cropdisease',
            name='image',
            field=models.ImageField(null=True, upload_to='diseases'),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
